#!/usr/bin/perl

my $n=0;
my $len;
my $hlen;
my $List_delim;
while ($ARGV[0] =~ m@^-@) {
    my $opt = shift @ARGV;
    if ($opt eq '--header'){
        $n = 1;
        @vals = split(/,/,shift @ARGV);
        $len = scalar(@vals);
        print '|'.join('|',@vals)."|\n";
        @vals = map {"---"} @vals;
        print '|'.join('|',@vals)."|\n";
        
    }
    elsif ($opt eq '--list-delimiter' || $opt eq '-D') {
        $list_delim = shift @ARGV;
    }
}
while(<>) {
    s/\r?\n\z//;
    chomp;
    if ($n==0 && m@^\#@) {
        s@^\#@@;
    }
    my (@vals) = split(/\t/,$_);
    if ($list_delim) {
        @vals = map {s@\|@$list_delim@gx; $_} @vals;
    }
    else {
        @vals = map {s@\|@, @g; $_} @vals;
    }
    @vals = map {s@^\>@`>`@g; $_} @vals;
    if (!$hlen) {
        $hlen = scalar(@vals);
    }
    while (scalar(@vals) < $hlen) {
        push(@vals, '');
    }
    print '|'.join('|',@vals)."|\n";
    $nulen = scalar(@vals);
    if ($n > 0) {
        if ($len ne $nulen) {
            print STDERR "MISMATCH: $len != $nulen\n";
        }
    }
    $len = $nulen;
    if ($n ==0) {
        @vals = map {"---"} @vals;
        print '|'.join('|',@vals)."|\n";
    }
    $n++;
}
